"""Blender round-trip for SkeletalMesh geometry: game asset -> .blend -> playable mod.

    extract_blend(game_rel)             -> writes <project>/<asset>.blend for the user to edit
    build_from_blend(game_rel, blend)   -> rebuilds every LOD from that .blend and packs a mod

The user edits ONLY the top LOD. Lower LODs are regenerated by decimating the same edited
mesh to each LOD's original triangle ratio, so LOD popping keeps roughly the vanilla
character rather than needing three hand-edits.

WHAT MAY BE EDITED: vertices -- add, remove, move, subdivide, sculpt. Materials and their
count must stay as they are, and the armature must not be touched (glb_to_blend.py locks
it). Those two constraints are what keep a rebuild a value-only patch of the existing
section records; see atelier.handlers.mesh.rebuild_lod_buffers for why.
"""
import json
import os
import shutil
import subprocess
import sys

from atelier.config import ASSETS_MODS, CNW, USMAP, _CACHE, get_import_root, project_base
from atelier.handlers import mesh as _mesh
from atelier.handlers import meshmat as _meshmat
from atelier.handlers import meshsurvey as _survey
from atelier.tools import uat

_BLENDER_DIRS = (r"C:\Program Files\Blender Foundation",
                 r"C:\Program Files (x86)\Blender Foundation")
_SCRIPTS = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "blender")


def find_blender():
    """Locate blender.exe. ATELIER_BLENDER wins; otherwise pick the highest-versioned
    install (a machine can have several side by side)."""
    env = os.environ.get("ATELIER_BLENDER")
    if env and os.path.exists(env):
        return env
    found = []
    for root in _BLENDER_DIRS:
        if not os.path.isdir(root):
            continue
        for name in os.listdir(root):
            exe = os.path.join(root, name, "blender.exe")
            if os.path.exists(exe):
                found.append((name, exe))
    if not found:
        raise RuntimeError(
            "Blender not found. Install Blender 4.x/5.x, or set ATELIER_BLENDER to "
            "blender.exe.")
    found.sort(key=lambda p: [int(x) if x.isdigit() else x for x in p[0].replace("Blender", "").split()])
    return found[-1][1]


def _run_blender(script, args, label):
    exe = find_blender()
    cmd = [exe, "--background", "--python", os.path.join(_SCRIPTS, script), "--"] + list(args)
    r = subprocess.run(cmd, capture_output=True, text=True, creationflags=CNW)
    out = (r.stdout or "") + (r.stderr or "")
    # Blender exits 0 even when the embedded script raises, so success must be judged by
    # the marker the script prints -- never by the return code alone.
    if f"{label}_OK" not in out:
        tail = "\n".join(l for l in out.splitlines() if l.strip())[-1500:]
        raise RuntimeError(f"Blender step {script} failed:\n{tail}")
    return out


def extract_blend(game_rel, base_path=None, blend_path=None, force=False, with_materials=True):
    """Decode a mesh's top LOD to a .blend in the active project folder.

    Refuses up front on a format this pipeline cannot rebuild. The check runs here, at
    extract time, rather than at build time on purpose: the expensive, unrecoverable thing
    a user spends on a mesh is the sculpting between the two, and discovering afterwards
    that the asset was never packable wastes all of it. `force` extracts anyway, which is
    useful for inspecting an unsupported asset without intending to ship it.
    """
    base = base_path or _resolve_base(game_rel)
    report = _survey.probe(base)
    if report["status"] != "ok" and not force:
        raise RuntimeError(
            _survey.verdict_text(report)
            + "\n\nThis mesh cannot be rebuilt by the current pipeline. Pass force=True "
              "(CLI: --force 1) to extract it for inspection anyway -- but a build will "
              "fail or produce a broken package.")
    m = _mesh.Mesh(base)
    blend_path = blend_path or (project_base(game_rel) + ".blend")
    os.makedirs(os.path.dirname(blend_path), exist_ok=True)

    # Resolve the mesh's materials to their textures and stage those into the project, so the
    # .blend opens with the character's real surfaces wired up and painting them in Blender edits
    # the very files the texture pipeline ships. Never fatal: a mesh whose materials can't be
    # resolved is still perfectly editable as geometry.
    manifest_path, manifest = blend_path + ".mat.json", None
    if with_materials:
        try:
            manifest = _meshmat.build_manifest(game_rel, m, work_base=base)
            json.dump(manifest, open(manifest_path, "w"), indent=1)
        except Exception as e:
            print(f"[meshedit] material/texture staging skipped: {e}", file=sys.stderr, flush=True)
            manifest = None

    glb = blend_path + ".tmp.glb"
    _mesh.export_glb(m, 0, glb)
    try:
        args = [glb, blend_path] + ([manifest_path] if manifest else [])
        out = _run_blender("glb_to_blend.py", args, "BLEND")
    finally:
        if os.path.exists(glb):
            os.remove(glb)
    info = next((l for l in out.splitlines() if l.startswith("BLEND_OK")), "")
    textures = sorted(t for t, r in (manifest or {}).get("textures", {}).items() if r.get("path"))
    return {"blend": blend_path, "info": info.strip(), "lods": len(m.lods),
            "warnings": report["warnings"] + ((manifest or {}).get("warnings") or []),
            "preflight": _survey.verdict_text(report),
            "textures": textures,
            "materials": sorted((manifest or {}).get("slots", {}).keys())}


def stage_mesh(game_rel, stage, blend_path=None, base_path=None):
    """Rebuild every LOD from the edited .blend into an export stage, ready to be packed.

    LOD0 uses the mesh as edited; each lower LOD is decimated to the triangle ratio that
    LOD originally had relative to LOD0, so the vanilla LOD progression is preserved.
    Materials a lower LOD never had are simply not looked up -- matching how the cooker
    drops whole sections from distant LODs.

    Staging is separate from packing so a mesh edit can share ONE pak with the texture and
    material edits for the same character (texture.build_mod), instead of shipping a second
    mod that competes with the first.
    """
    base = base_path or _resolve_base(game_rel)
    blend_path = blend_path or (project_base(game_rel) + ".blend")
    if not os.path.exists(blend_path):
        raise RuntimeError(f"no .blend at {blend_path} -- run extract first")
    m = _mesh.Mesh(base)

    lod0_tris = sum(s["num_tris"] for s in m.lods[0]["sections"])
    applied = []
    for i, lod in enumerate(m.lods):
        ratio = 1.0 if i == 0 else (sum(s["num_tris"] for s in lod["sections"]) / lod0_tris)
        glb = f"{blend_path}.lod{i}.glb"
        if os.path.exists(glb):
            os.remove(glb)        # never let a previous run's output be mistaken for fresh
        out = _run_blender("blend_to_glb.py", [blend_path, glb, f"{ratio:.6f}"], "GLB")
        mats = next((l[len("MATERIALS "):] for l in out.splitlines()
                     if l.startswith("MATERIALS ")), "")
        have = set(mats.split("|")) if mats else set()
        need = {m.materials[s["mat"]]["slot_name"] for s in lod["sections"]}
        missing = sorted(n for n in need if n and n not in have)
        if missing:
            raise RuntimeError(
                f"LOD{i} (decimate ratio {ratio:.3f}) lost every face of: {', '.join(missing)}. "
                f"That section would be empty, which the engine does not tolerate. Give those "
                f"materials more geometry, or raise the LOD ratio.")
        secs = _mesh.glb_to_sections(m, i, glb)
        info = m.rebuild_lod(i, secs)
        applied.append({"lod": i, "ratio": round(ratio, 4), **info})
        os.remove(glb)

    target = os.path.join(stage, *_pak_dir(game_rel).split("/"))
    asset_name = os.path.basename(base)
    m.save(target, asset_name)

    # The engine reads the SkeletalMesh export's SerialSize from the .uasset; every LOD
    # resize changes it (and the .ubulk length feeds into UAssetTool's formula), so this
    # must run before packing or the package fails to load with a size mismatch.
    uasset = os.path.join(target, asset_name + ".uasset")
    r = uat(["fix", os.path.abspath(uasset), USMAP])
    if r.returncode != 0:
        raise RuntimeError("uat fix failed: " + ((r.stdout or "") + (r.stderr or ""))[-400:])
    return {"applied": applied, "stage": stage, "uasset": uasset}


def build_from_blend(game_rel, blend_path=None, base_path=None, out_dir=None, mod_name=None):
    """Rebuild every LOD from the edited .blend and pack a mesh-only mod (the CLI path).

    The app packs mesh edits through texture.build_mod instead, so they share one pak with
    the character's texture edits; this stays the standalone route.
    """
    name = mod_name or (os.path.basename(game_rel).replace(".uasset", "") + "_MeshEdit")
    out_dir = out_dir or ASSETS_MODS
    stage = os.path.join(_CACHE, "mesh_stage", name)
    shutil.rmtree(stage, ignore_errors=True)
    staged = stage_mesh(game_rel, stage, blend_path=blend_path, base_path=base_path)
    applied = staged["applied"]

    os.makedirs(out_dir, exist_ok=True)
    base_out = os.path.join(out_dir, f"{name}_9999999_P")
    for ext in (".pak", ".ucas", ".utoc"):
        if os.path.exists(base_out + ext):
            os.remove(base_out + ext)
    r = uat(["create_mod_iostore", os.path.abspath(base_out), os.path.abspath(stage),
             "--usmap", USMAP])
    if not os.path.exists(base_out + ".utoc"):
        raise RuntimeError("create_mod_iostore failed: " +
                           ((r.stdout or "") + (r.stderr or ""))[-400:])
    return {"applied": applied, "stage": stage, "name": name,
            "pak": base_out + ".pak", "mod": base_out}


def _pak_dir(game_rel):
    from atelier.handlers.texture import pak_game_path
    return os.path.dirname(pak_game_path(game_rel))


def _resolve_base(game_rel):
    """Extracted vanilla stem for the mesh, pulling it out of the paks if it isn't cached yet."""
    from atelier.handlers.texture import ensure_work_base
    base = ensure_work_base(game_rel)
    if not base or not os.path.exists(base + ".uasset"):
        raise RuntimeError(f"mesh not found in the game paks: {game_rel}")
    return base


def _main(argv):
    if len(argv) < 2 or argv[0] not in ("extract", "build", "preflight"):
        print("usage:\n"
              "  python -m atelier.handlers.meshedit preflight <game_rel> [--base PATH]\n"
              "  python -m atelier.handlers.meshedit extract <game_rel> [--base PATH] [--blend PATH] [--force 1]\n"
              "  python -m atelier.handlers.meshedit build   <game_rel> [--base PATH] [--blend PATH] [--name N]")
        return 2
    cmd, game_rel = argv[0], argv[1]
    opts = {}
    rest = argv[2:]
    for i in range(0, len(rest) - 1, 2):
        if rest[i].startswith("--"):
            opts[rest[i][2:]] = rest[i + 1]
    if cmd == "preflight":
        rec = _survey.preflight(game_rel, base_path=opts.get("base"))
        print(_survey.verdict_text(rec))
        return 0 if rec["status"] == "ok" else 1
    if cmd == "extract":
        r = extract_blend(game_rel, base_path=opts.get("base"), blend_path=opts.get("blend"),
                          force=bool(opts.get("force")))
        print(r["preflight"])
        print(f"\nblend: {r['blend']}\n{r['info']}\nLODs in asset: {r['lods']} "
              f"(you edit the top one; the rest are generated on build)")
    else:
        r = build_from_blend(game_rel, blend_path=opts.get("blend"),
                             base_path=opts.get("base"), mod_name=opts.get("name"))
        for a in r["applied"]:
            print(f"  LOD{a['lod']}: decimate={a['ratio']} verts={a['total_nv']} "
                  f"tris={a['n_idx']//3} idx{a['idx_stride']*8}bit")
        print("mod:", r["pak"])
    return 0


if __name__ == "__main__":
    raise SystemExit(_main(sys.argv[1:]))
